### ISSUE TITLE
Wikiについてのコメント

### ISSUE THREAD

**Issue by TetraMiyazaki** [furukawa-laboratory/rookies_workout_2021#1]
全体の方針がわからない．やることはわかるけど，何を目指しているのかがわからない．
具体的には
- 全体の目的が書かれていない．
- Mission Success Criteriaがないので勝利条件わからない・

なんでこのメニューを学ぶ必要があるのかがわからない．この技術の先に何があるのかどういう世界が広がっているのかがわからない．
具体的には
- https://github.com/furukawa-laboratory/three_months_course_2020/blob/master/Menu.md のような感じで世界感を示されていない．

**Comment by tanacchi** [comment]
コメントありがとうございます！

> - 全体の目的が書かれていない．
> - Mission Success Criteriaがないので勝利条件わからない・
> - 世界感を示されていない．

3つ目に関しては３ヶ月コースにおける位置付けを示しました。
